### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by avstudnitz** [yireo/magento2-backend-reindexer#1]
The first release 0.0.1 is not compatible to Magento 2.2 yet, the master branch is because of the adjusted composer.json. Please create a new tag.

**Comment by jissereitsma** [comment]
Done. I've modified `composer.json` slightly to include 2.2 properly and a new tag is added. Let me know if this works for you.

**Comment by avstudnitz** [comment]
Waiting for Packagist to update... https://packagist.org/packages/yireo/magento2-backend-reindexer just shows 0.0.1.
Does it auto-update?

**Comment by jissereitsma** [comment]
I've used a different naming schedule for this module, which breaks my own release scripts that automatically apply tagging and all. I've now done it manually. Needed to bump to 0.0.3 though.

**Comment by avstudnitz** [comment]
Thanks, works now!
